name: educator
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  awesome_dialog: ^2.1.2
  bloc: ^8.0.3
  circular_countdown_timer: ^0.2.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get: ^4.6.1
  get_it: ^7.2.0
  image_picker: ^0.8.4+11
  intl: null
  menu_button: ^1.4.2+1
  queen_validators: ^0.2.3
  url_launcher: ^6.0.20
  path:
  path_provider:
  sqflite:
dev_dependencies:
  auto_route_generator: null
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Hacen
      fonts:
        - asset: assets/fonts/Hacen Tunisia.ttf
        - asset: assets/fonts/Hacen Tunisia Lt.ttf
        - asset: assets/fonts/Hacen Tunisia Bd.ttf
